# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Exemplo-firebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'


  # Pods for Exemplo-firebase

end
